---

## Need long time to update
- name: Update apt
  apt: update_cache=yes
  become: true
  become_user: root
  become_method: sudo

# Install Python Stuff
- name: Install python-dev, python-pip, python-virtualenv etc.
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ python }}"
  vars:
    python:
      - python3-dev
      - python3-pip
      - python3-venv
      - python-psycopg2
      - libpq-dev
      - python-selinux
      - python-semanage
      - policycoreutils-python-utils

- name: Install openjdk-11-jdk
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: openjdk-11-jdk

- name: Install utils
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: "{{ utils }}"
  vars:
    utils:
      - mc
      - net-tools
      - nfs-common

# Install Git
- name: Install git-core
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: git-core

# Install Database
- name: postgresql
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: postgresql

# Install curl
- name: curl
  become: true
  become_user: root
  become_method: sudo
  apt:
    name: curl

# nginx for deploy ckan
- name: include nginx for deploy
  include: nginx/nginx.yml
